### ISSUE TITLE
[BUG] Error: Did not receive X-CSRF-TOKEN

### ISSUE THREAD

**Issue by nixpc** [suufi/noblox.js#163]
It seems like there is currently a problem with ROBLOX where when you try and log in with noblox.js it will error and say how it did not receive a X-CSRF-TOKEN. Probably a new ROBLOX update that broke stuff.

Error log:
```
Stored relog failed. Trying with given.
Error: Did not receive X-CSRF-TOKEN
    at /root/robloxca/node_modules/noblox.js/lib/util/getGeneralToken.js:26:15
    at tryCatcher (/root/robloxca/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/robloxca/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/root/robloxca/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/root/robloxca/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/root/robloxca/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/root/robloxca/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/root/robloxca/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/root/robloxca/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/root/robloxca/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:456:21)
(node:23903) UnhandledPromiseRejectionWarning: Error: No cookie supplied and no cookie file available.
    at c (/root/robloxca/node_modules/noblox.js/lib/util/relog.js:77:9)
(node:23903) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23903) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

(A cookie was supplied and there is no issue there, I even tried giving it a fresh new cookie but it still doesn't work so yeah...)

**Comment by nixpc** [comment]
At 2020-07-17 00:19:12 UTC, it still worked.
Then on 2020-07-17 01:02:52 UTC the bot tried to rank someone but failed.
Therefore I assume ROBLOX changed something between those two times.

**Comment by Neztore** [comment]
Hi! Package version?

**Comment by nixpc** [comment]
This was the latest commit:
https://github.com/suufi/noblox.js/commit/7634658fc40bd7d360cf961dc6f04752abc7dc7c

I'll try updating and see if it works.

**Comment by nixpc** [comment]
All fixed, thanks for your help!
