### ISSUE TITLE
[BUG] Noblox.js causes circular dependency warning on node v14

### ISSUE THREAD

**Issue by Neztore** [suufi/noblox.js#195]
**Describe the bug**
The following is outputted:
```(node:41901) Warning: Accessing non-existent property 'func' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:672:11)
    at Object.get (internal/modules/cjs/loader.js:686:5)
    at Object.<anonymous> (/home/josh/Desktop/test/efewqefwfd/lib/index.js:23:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/josh/Desktop/test/index.js:1:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47```

**To Reproduce**
Steps to reproduce the behavior:
1. Run on node v14.
Sample test code:
```js
const n = require("./noblox.js");
async function test () {
    console.log(await n.getPlayerInfo(66592931));

}
test();

```

**Expected behavior**
Runs fine.

## Debugging done so far
I have set NODE_DEBUG=module and have got the following:
```MODULE 41901: RELATIVE: requested: ../../settings.json from parent.id /home/josh/Desktop/test/efewqefwfd/lib/util/threaded.js
MODULE 41901: looking for ["/home/josh/Desktop/test/efewqefwfd/lib/util"]
MODULE 41901: Module._load REQUEST ./options.js parent: /home/josh/Desktop/test/efewqefwfd/lib/index.js
MODULE 41901: RELATIVE: requested: ./options.js from parent.id /home/josh/Desktop/test/efewqefwfd/lib/index.js
MODULE 41901: looking for ["/home/josh/Desktop/test/efewqefwfd/lib"]
MODULE 41901: Module._load REQUEST ../settings.json parent: /home/josh/Desktop/test/efewqefwfd/lib/index.js
(node:41901) Warning: Accessing non-existent property 'func' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:672:11)
    at Object.get (internal/modules/cjs/loader.js:686:5)
    at Object.<anonymous> (/home/josh/Desktop/test/efewqefwfd/lib/index.js:23:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/josh/Desktop/test/index.js:1:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```
I think this suggests an issue where the index.js is being requested (which is circular.
Another potential source could be that options.js does not have a `func` function - so perhaps options is requiring something which also requires it?

A potential fix was submitted in #193 . It does not fix the issue

### Related issues/Pull requests:
[Related nodejs source](https://github.com/nodejs/node/blob/726143e683738b0e60580bdc247e6cfa60a0783a/lib/internal/modules/cjs/loader.js#L662)
[NodeJS docs](https://nodejs.org/dist/latest-v14.x/docs/api/modules.html)

### Fixing it
- We could either try to remove the circular dependency, or find some other way to check for "func" that does not cause the error? Circular dependencies are meant to be supported.
- Do we need to do anything else to support ESM modules?

**Comment by Neztore** [comment]
Command used to produce these traces:
`./node-v14.13.0-linux-x64/bin/node --trace-warnings  index.js --trace-warnings`
Where the first part is the path to the v14 node binary.
