### ISSUE TITLE
Timeout issue with onJoinRequestHandle

### ISSUE THREAD

**Issue by aj2958** [suufi/noblox.js#255]
I am making a bot to handle all join requests but it keeps timing out and the socket is hanging up?

Console output for it:
`Unhandled rejection: RequestError: Error: socket hang up
RequestError: Error: socket hang up
    at new RequestError (D:\vulpine-utility\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (D:\vulpine-utility\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (D:\vulpine-utility\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (D:\vulpine-utility\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (D:\vulpine-utility\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketCloseListener (_http_client.js:443:11)
    at TLSSocket.emit (events.js:327:22)
    at net.js:673:12
    at TCP.done (_tls_wrap.js:563:7) {
  cause: Error: socket hang up
      at connResetException (internal/errors.js:617:14)
      at TLSSocket.socketCloseListener (_http_client.js:443:25)
      at TLSSocket.emit (events.js:327:22)
      at net.js:673:12
      at TCP.done (_tls_wrap.js:563:7) {
    code: 'ECONNRESET'
  },
  error: Error: socket hang up
      at connResetException (internal/errors.js:617:14)
      at TLSSocket.socketCloseListener (_http_client.js:443:25)
      at TLSSocket.emit (events.js:327:22)
      at net.js:673:12
      at TCP.done (_tls_wrap.js:563:7) {
    code: 'ECONNRESET'
  },
  options: {
    forever: true,
    agentOptions: { maxSockets: Infinity, keepAlive: true },
    simple: false,
    gzip: true,
    timeout: 10000,
    method: 'GET',
    jar: null,
    resolveWithFullResponse: true,
    followRedirect: [Function (anonymous)],
    headers: {
      cookie: [Redacted];'
    },
    uri: 'https://groups.roblox.com/v1/groups/3503317/join-requests?limit=100&sortOrder=Asc&cursor=',
    callback: [Function: RP$callback],
    transform: undefined,
    transform2xxOnly: false
  },
  response: undefined
}

Unhandled rejection: TimeoutError: operation timed out
SubError [TimeoutError]: operation timed out
    at afterTimeout (D:\vulpine-utility\node_modules\bluebird\js\release\timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (D:\vulpine-utility\node_modules\bluebird\js\release\timers.js:76:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)`

**Comment by BillyH-0167** [comment]
Tried replying this morning but didnt have chance, to fix your issue you need to catch the event error with:


```js
<event>.on("error", function(err) {

//code to handle it
})

```
