### ISSUE TITLE
Unhandled rejection Error: Cannot get CSRF: You are not logged in.

### ISSUE THREAD

**Issue by hackhack6776** [suufi/noblox.js#277]
Using noblox.js for roblox group rank bot!
I checked the output or whatever its called and got this every time I tried to rank somebody:
Unhandled rejection Error: Cannot get CSRF: You are not logged in.
    at getGeneralToken (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/util/getGeneralToken.js:25:11)
    at /rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/util/getGeneralToken.js:50:12
    at Object.add (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/cache/wrap.js:15:18)
    at module.exports (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/cache/addIf.js:21:15)
    at /rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/cache/wrap.js:12:7
    at Promise._execute (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/promise.js:103:10)
    at module.exports (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/internal/promise.js:6:10)
    at wrap (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/cache/wrap.js:11:12)
    at Object.module.exports [as wrap] (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/cache/wrap.js:25:10)
    at exports.func (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/util/getGeneralToken.js:49:16)
    at runWithToken (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/group/setRank.js:61:10)
    at /rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/group/setRank.js:74:14
    at tryCatcher (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/async.js:102:5)

**Comment by Neztore** [comment]
Have you used `setCookie` with your Roblox cookie?
This suggests you have not.
`Unhandled rejection Error: Cannot get CSRF: You are not logged in.` is thrown whenever you try to use an authenticated method, while not being authenticated. 

See the [Authentication tutorial](https://noblox.js.org/tutorial-Authentication.html)

**Comment by hackhack6776** [comment]
> Have you used `setCookie` with your Roblox cookie?
> This suggests you have not.
> `Unhandled rejection Error: Cannot get CSRF: You are not logged in.` is thrown whenever you try to use an authenticated method, while not being authenticated.
> 
> See the [Authentication tutorial](https://noblox.js.org/tutorial-Authentication.html)

**Comment by hackhack6776** [comment]
Still not working :(

**Comment by hackhack6776** [comment]
My code:

/*INSERT GROUP ID AND COOKIE BELOW*/

var groupId = 9467607; // << Replace 12345 with your Group Id
var cookie = "secret"; // << Put your account cookie inside of the quotes

/*INSERT GROUP ID AND COOKIE ABOVE*/

const express = require("express");
const rbx = require("noblox.js");
const app = express();

app.use(express.static("public"));

async function startApp() {
  //await rbx.setCookie(cookie);
  rbx.setCookie(cookie).then(function() {
      //Use COOKIE from our .env file.
      console.log("Logged in!");
    })
    .catch(function(err) {
      console.log("Unable to log in!", err);
    });
  let currentUser = await rbx.getCurrentUser();
  console.log(currentUser.UserName);
}
startApp();

app.get("/ranker", (req, res) => {
  var User = req.param("userid");
  var Rank = req.param("rank");

  rbx.setRank(groupId, parseInt(User), parseInt(Rank));
  res.json("Ranked!");
});

const listener = app.listen(process.env.PORT, () => {
  console.log("Your app is listening on port " + listener.address().port);
});

**Comment by Neztore** [comment]
Hi there. Please consider joining the [Discord server](https://discord.gg/R5GVSyTVGv) for support.
You are not using promises correctly: Your code does not 'wait' until setCookie is complete, before running getCurrentUser.

See the [Promises](https://noblox.js.org/tutorial-Promises.html) tutorial, or Google "Javascript Promises". They are a topic that is frequently misunderstood in Javascript - and it would be best if you learn them before continuing. 
The following code:
```js
setCookie(...).then(function () {
// ...
})
```
Will run whatever is in the .then function (in this case a comment with `...`) once the promise has resolved. Any content not in this block will run immediately afterwards.
