### ISSUE TITLE
[BUG] Unhandled rejection Error: Cannot get CSRF: You are not logged in.

### ISSUE THREAD

**Issue by hackhack6776** [suufi/noblox.js#279]
HELP!
Using noblox.js for roblox group rank bot!
I checked the output or whatever its called and got this every time I tried to rank somebody:
Unhandled rejection Error: Cannot get CSRF: You are not logged in.
at getGeneralToken (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/util/getGeneralToken.js:25:11)
at /rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/util/getGeneralToken.js:50:12
at Object.add (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/cache/wrap.js:15:18)
at module.exports (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/cache/addIf.js:21:15)
at /rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/cache/wrap.js:12:7
at Promise._execute (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/debuggability.js:384:9)
at Promise._resolveFromExecutor (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/promise.js:518:18)
at new Promise (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/promise.js:103:10)
at module.exports (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/internal/promise.js:6:10)
at wrap (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/cache/wrap.js:11:12)
at Object.module.exports [as wrap] (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/cache/wrap.js:25:10)
at exports.func (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/util/getGeneralToken.js:49:16)
at runWithToken (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/group/setRank.js:61:10)
at /rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/noblox.js/4.8.3/node_modules/noblox.js/lib/group/setRank.js:74:14
at tryCatcher (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/promise.js:547:31)
at Promise._settlePromise (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/promise.js:604:18)
at Promise._settlePromise0 (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/promise.js:649:10)
at Promise._settlePromises (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/promise.js:729:18)
at _drainQueueStep (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/async.js:93:12)
at _drainQueue (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/async.js:86:9)
at Async._drainQueues (/rbd/pnpm-volume/a5b46a91-8b55-4997-accb-94dd19652dc5/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/async.js:102:5)

**Comment by Neztore** [comment]
Duplicate #277
