### ISSUE TITLE
[BUG] How do I login?

### ISSUE THREAD

**Issue by AceKiron** [suufi/noblox.js#287]
**Describe the bug**
I'm trying to create new developer products using noblox.js, I have 4.8.4 installed.

**To Reproduce**
1. Start your code with the following snippet:
```js
const noblox = require("noblox.js");
let user;

(async function() {
  await noblox.setCookie("[REDACTED] (this is actually the correct cookie)");
  user = await noblox.getCurrentUser();
}());
```
2. Use `noblox.addDeveloperProduct` to try to create a new developer product.
3. Get the following error:
```
Unhandled rejection Error: You are not logged in
    at /rbd/pnpm-volume/c7f0aecb-3bb5-46a3-916f-c7b45f15fc89/node_modules/.registry.npmjs.org/noblox.js/4.8.4/node_modules/noblox.js/lib/game/checkDeveloperProductName.js:34:13
    at tryCatcher (/rbd/pnpm-volume/c7f0aecb-3bb5-46a3-916f-c7b45f15fc89/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/rbd/pnpm-volume/c7f0aecb-3bb5-46a3-916f-c7b45f15fc89/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/rbd/pnpm-volume/c7f0aecb-3bb5-46a3-916f-c7b45f15fc89/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/rbd/pnpm-volume/c7f0aecb-3bb5-46a3-916f-c7b45f15fc89/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/rbd/pnpm-volume/c7f0aecb-3bb5-46a3-916f-c7b45f15fc89/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/rbd/pnpm-volume/c7f0aecb-3bb5-46a3-916f-c7b45f15fc89/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/rbd/pnpm-volume/c7f0aecb-3bb5-46a3-916f-c7b45f15fc89/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/rbd/pnpm-volume/c7f0aecb-3bb5-46a3-916f-c7b45f15fc89/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/rbd/pnpm-volume/c7f0aecb-3bb5-46a3-916f-c7b45f15fc89/node_modules/.registry.npmjs.org/bluebird/3.7.2/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

**Expected behavior**
I expected it to create a new developer product for me.

**Additional context**
Here are the arguments I passed into `noblox.addDeveloperProduct`:
6161238436, "Example name", 100, "Example description"

**Comment by Neztore** [comment]
It doesn't look like you are quite using promises correctly.

if you want this to function as expected, you must include any authenticated code **within** the async function.
Your addDeveloperProduct code is running before setCookie is complete.
[Promise tutorial](https://noblox.js.org/tutorial-Promises.html)

i.e.:
```js
const noblox = require("noblox.js");
let user;

(async function() {
  await noblox.setCookie("[REDACTED] (this is actually the correct cookie)");
  user = await noblox.getCurrentUser();
  await noblox.addDeveloperProduct(...);
}());
```

Alternatively, handle the promise returned by the async function.

**Comment by AceKiron** [comment]
> It doesn't look like you are quite using promises correctly.
> 
> if you want this to function as expected, you must include any authenticated code **within** the async function.
> Your addDeveloperProduct code is running before setCookie is complete.
> [Promise tutorial](https://noblox.js.org/tutorial-Promises.html)

This doesn't seem to be the problem, as addDeveloperProduct is being run after setCookie completed. Proof of this is that the user variable wasn't undefined or null.
```
{
  UserID: 2417896848,
  UserName: 'DonationBotLua',
  RobuxBalance: 0,
  ThumbnailUrl: 'https://tr.rbxcdn.com/6b815a4247857086c68bae92b9007fc9/352/352/Avatar/Png',
  IsAnyBuildersClubMember: false,
  IsPremium: false
}
```

**Comment by AceKiron** [comment]
Actually, it turned out I used place id instead of game id, I feel like noblox.js should detect this tho and automatically fix it.
