### ISSUE TITLE
Login Issue [Funcaptcha]

### ISSUE THREAD

**Issue by coolguzman11** [suufi/noblox.js#30]
ROBLOX has integrated a funcaptcha.. unable to login. 

2018-12-22T23:05:41.313868+00:00 app[worker.1]: Error: Login failed: You must pass the robot test before logging in.
2018-12-22T23:05:41.313873+00:00 app[worker.1]:     at /app/node_modules/noblox.js/lib/user/login.js:54:17
2018-12-22T23:05:41.313875+00:00 app[worker.1]:     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2018-12-22T23:05:41.313878+00:00 app[worker.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
2018-12-22T23:05:41.313880+00:00 app[worker.1]:     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
2018-12-22T23:05:41.313882+00:00 app[worker.1]:     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
2018-12-22T23:05:41.313883+00:00 app[worker.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:694:18)
2018-12-22T23:05:41.313885+00:00 app[worker.1]:     at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)
2018-12-22T23:05:41.313887+00:00 app[worker.1]:     at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)
2018-12-22T23:05:41.313888+00:00 app[worker.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)
2018-12-22T23:05:41.313890+00:00 app[worker.1]:     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14)
2018-12-22T23:05:41.313892+00:00 app[worker.1]:     at runCallback (timers.js:705:18)
2018-12-22T23:05:41.313893+00:00 app[worker.1]:     at tryOnImmediate (timers.js:676:5)
2018-12-22T23:05:41.313895+00:00 app[worker.1]:     at processImmediate (timers.js:658:5)

**Comment by JonasTheGamer** [comment]
Was it solved?

**Comment by coolguzman11** [comment]
Yes, I was given a bypass.

**Comment by JonasTheGamer** [comment]
Which was?

**Comment by landoxn** [comment]
Do you have the bypass? I need it.
