### ISSUE TITLE
[ERROR] Unhandled rejection Error: Follow failed

### ISSUE THREAD

**Issue by Emilius123** [suufi/noblox.js#65]
Hello! I am coding a following bot. For testing I just made a Little bit of Code that follows some random dude. Seemingly it doesn't…

> var rbx = require('noblox.js')

> var ProgressBar = require('progress')

> var js = require('JSONStream')

> var fs = require('fs')

> var group = 0

> var cookie = "--MyCookie--"

> var logged = rbx.cookieLogin(cookie)

>  .then(function () {
>      console.log(`Succesfully logged in as ${logged}!`)
>      var userId = 1044994841;
>      rbx.follow(userId)
 >     .then(function () {
>console.log("WOW!")
 >     })

>  })

Here's the output:

> node app.js
Succesfully logged in as [object Promise]!
Unhandled rejection Error: Follow failed
    at C:\Users\emeld\Desktop\node_modules\noblox.js\lib\user\follow.js:33:15
    at tryCatcher (C:\Users\emeld\Desktop\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\emeld\Desktop\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\Users\emeld\Desktop\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\Users\emeld\Desktop\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\Users\emeld\Desktop\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (C:\Users\emeld\Desktop\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\emeld\Desktop\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\emeld\Desktop\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\emeld\Desktop\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
What can I do

**Comment by suufi** [comment]
The follow function is working for me. Are you sure you're not blocked by that user?

**Comment by Emilius123** [comment]
What function?

**Comment by Emilius123** [comment]
Yep. I even tried following my own main where I know it didn't block me.

**Comment by Emilius123** [comment]
But on the Roblox API discord the user --- said 

> :face_palm: Disregard, I am an idiot and forgot to change my privacy settings

**Comment by suufi** [comment]
You can try and see if that'll change anything. As far as I'm concerned, the follow function is working. I'll be making some changes that show specific error messages really soon.
