### ISSUE TITLE
[BUG]getPlayers returns Error 400: Bad Request

### ISSUE THREAD

**Issue by TimeOverseer** [suufi/noblox.js#77]
Tried to use the getPlayers function but it returned this in the console: 
Error: 400 : Bad Request
    at Request._callback (C:\Users\zombi\Desktop\Carl\node_modules\noblox.js\lib\group\getPlayers.js:17:55)
    at Request.self.callback (C:\Users\zombi\Desktop\Carl\node_modules\request\request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.<anonymous> (C:\Users\zombi\Desktop\Carl\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:203:13)
    at IncomingMessage.<anonymous> (C:\Users\zombi\Desktop\Carl\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:291:20)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1161:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

This is my code:
Roblox.getPlayers(2654608, 255).catch(function(error) {
		console.log(error);
	});

**Comment by General-Scripter** [comment]
getPlayers is expecting the rolesetId, not the rankId. This should probably be made clearer, but you'll have to inspect element on the group page, select the role dropdown menu and copy the numbers afer "role-" to get the rolesetId.
![chrome_fdsvjxTj90](https://user-images.githubusercontent.com/54756166/64432886-51b53980-d0b5-11e9-81b5-830e731f3281.png)
