### ISSUE TITLE
[Library Issue]

### ISSUE THREAD

**Issue by Practicalx** [suufi/noblox.js#81]
client.on('message', msg => {
    if(msg.content.substring(0,3) === ';wl'){
        try {
            rbx.handleJoinRequest(groupid,msg.content.substring(4,msg.content.length),true)
        }        catch(err) {
            msg.channel.send(`${msg.content.substring(4,msg.content.length)} has not submitted a join request.`)
        };
};
}); 

Is my current code. I'm intentionally creating this error to see if it will catch. It's not catching at all. Instead of catching, I get this error.

`Unhandled rejection Error: No join request was found with that username
    at C:\discordbots\Gateway\node_modules\noblox.js\lib\group\handleJoinRequest.js:45:17
    at tryCatcher (C:\discordbots\Gateway\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\discordbots\Gateway\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\discordbots\Gateway\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\discordbots\Gateway\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\discordbots\Gateway\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (C:\discordbots\Gateway\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\discordbots\Gateway\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\discordbots\Gateway\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\discordbots\Gateway\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)`

**Comment by Pokemonjpups** [comment]
I'm pretty sure this is because you aren't awaiting the function call. Either add `.then().catch()` to it, or use the `await` keyword
